version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    volumes:
      - ${DATA_PATH}/rabbitmq/logs:/var/log/rabbitmq/log
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    network_mode: bridge
    environment:
      - RABBITMQ_ERLANG_COOKIE=docker-compose-rabbitmq
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin