package br.com.otto.rabbitmq.consumer

object QueueDefinition {
    const val FRAUDULENT_ACCOUNT_QUEUE = "FRAUDULENT-ACCOUNT-QUEUE"
    const val FRAUDULENT_ACCOUNT_DIRECT_EXCHANGE = "FRAUDULENT-ACCOUNT-DIRECT-EXCHANGE"
    const val FRAUDULENT_ACCOUNT_BINDING_KEY = "TO-FRAUDULENT-ACCOUNT-QUEUE"
    const val FRAUDULENT_ACCOUNT_DLQ_EXCHANGE = "FRAUDULENT-ACCOUNT-DLQ-EXCHANGE"
    const val FRAUDULENT_ACCOUNT_DLQ_QUEUE = "FRAUDULENT-ACCOUNT-DLQ-QUEUE"
    const val FRAUDULENT_ACCOUNT_DLQ_BINDING_KEY = "FRAUDULENT_ACCOUNT-TO-DLQ"
}